[package]
name = "invaders"
version = "0.1.0"
authors= ["wilsntn <wilcson.denner@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
rusty_audio = "1.1.4"
rusty_time = "0.11.0"